name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
  # pull_request:

# permissions:
#   actions: read
#   contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build frontend and backend
      - name: Build apps
        run: |
          npx nx build web --configuration=production --skip-nx-cache
          npx nx build api --configuration=production --skip-nx-cache
        env:
          NX_SKIP_NX_CLOUD: true
      - name: List main folder
        run: ls
      - name: List web folder
        run: ls web
      - name: List web dist folder
        run: ls web/dist
      - name: List api folder
        run: ls api
      - name: List api dist folder
        run: ls api/dist

      # 5️⃣ Copy files to EC2
      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'web/dist/*,api/dist/*,node_modules,api/src/db.json'
          target: /tmp/deploy

      # 6️⃣ SSH into EC2 and move files
      - name: SSH and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create directories if not exist
            sudo mkdir -p /var/www/html/portfolio-2025/web
            sudo mkdir -p /var/www/html/portfolio-2025/api

            # Copy frontend build
            sudo rm -rf /var/www/html/portfolio-2025/web/*
            sudo cp -r /tmp/deploy/web/dist/* /var/www/html/portfolio-2025/web/

            # Copy backend build
            sudo rm -rf /var/www/html/portfolio-2025/api/*
            sudo cp -r /tmp/deploy/api/dist/* /var/www/html/portfolio-2025/api/
            sudo cp -r /tmp/deploy/node_modules /var/www/html/portfolio-2025/api/
            sudo cp /tmp/deploy/api/src/db.json /var/www/html/portfolio-2025/api/

            # Restart backend
            pm2 restart api || pm2 start /var/www/html/portfolio-2025/api/main.js --name api

            # Clean up temp
            rm -rf /tmp/deploy
